// GENERATED by scripts/gen-rpcs.ts from dex-evm deployments/chains.json `.rpc`: do not edit.
// Refresh the list with scripts/refresh-rpcs.ts, then regenerate.

export const CHAIN_RPCS: Readonly<Record<number, readonly string[]>> = {
  1: ['https://ethereum-rpc.publicnode.com', 'https://0xrpc.io/eth'],
  56: ['https://bsc-rpc.publicnode.com', 'https://bsc-dataseed.binance.org'],
  137: ['https://polygon-bor-rpc.publicnode.com', 'https://poly.api.pocket.network'],
  143: ['https://rpc1.monad.xyz', 'https://rpc2.monad.xyz'],
  196: ['https://rpc.xlayer.tech', 'https://xlayerrpc.okx.com'],
  999: ['https://rpc.hyperliquid.xyz/evm'],
  4663: ['https://robinhood-rpc.publicnode.com', 'https://rpc.mainnet.chain.robinhood.com'],
  5042: ['https://arc-rpc.publicnode.com', 'https://rpc.beamrpc.com'],
  8453: ['https://base-rpc.publicnode.com', 'https://developer-access-mainnet.base.org'],
  42161: ['https://arbitrum-one-rpc.publicnode.com', 'https://arb1.arbitrum.io/rpc'],
  43114: ['https://avalanche-c-chain-rpc.publicnode.com', 'https://rpc-avalanche.blockmachine.io'],
  5042002: ['https://rpc.blockdaemon.testnet.arc.network', 'https://rpc.testnet.arc.network'],
};
