// Quartic I-spline preset grid: types, the slicing rule, and the tracked slice.
//
// SSoT (machine) = dex/research/stable-core/out/spline_shared_grid.json, 6.6 MB and gitignored,
// so it is NOT readable from a clean sdk clone. `spline_grid.json` next to this file is the
// tracked slice (portable presets only: knot grid + weights), regenerated by
// `bun scripts/gen-curve-grid-fixture.ts` and re-verified against the full grid by grid.test.ts
// whenever that artifact is present locally.

import { resolve } from 'node:path';

/** Absolute path of the full (untracked) fit output, for the local-only parity check. */
export const GRID_PATH = resolve(
  new URL('.', import.meta.url).pathname,
  '../../../..',
  'dex/research/stable-core/out/spline_shared_grid.json',
);

export interface GridPreset {
  portable: boolean;
  w: number[];
}
export interface GridWall {
  W: number;
  shared: { interiorX: number[] };
  presets: Record<string, GridPreset>;
}
export interface SplineGrid {
  regimes: string[];
  pinVariants: string[];
  walls: Record<string, GridWall>;
}

/** Keep only what the SDK consumes: regime order, wall width, shared knots, portable weights. */
export function sliceGrid(g: SplineGrid): SplineGrid {
  return {
    regimes: g.regimes,
    pinVariants: g.pinVariants,
    walls: Object.fromEntries(
      Object.entries(g.walls).map(([k, w]) => [
        k,
        {
          W: w.W,
          shared: { interiorX: w.shared.interiorX },
          presets: Object.fromEntries(
            Object.entries(w.presets)
              .filter(([, p]) => p.portable)
              .map(([r, p]) => [r, { portable: p.portable, w: p.w }]),
          ),
        },
      ]),
    ),
  };
}
