// Generated by `bun scripts/gen.ts` from the sibling dex/shared checkouts. Do not edit by hand —
// `bun run gen:check` fails the build when this file and the contracts disagree.

/**
 * Solidity enum ordinals and internal constants
 * @module @btr-protocol/sdk/abis
 *
 * solc keeps neither in the ABI, so both are parsed out of the declaring `.sol` file. Never
 * hand-write an ordinal: `OpType` is grouped by timelock tier and `Resource` by meaning, so both
 * renumber whenever a member joins a group.
 */

/** Second arg of `Admin.requestOp` / `execute` / `cancelTimelock`. Grouped by timelock tier, so a member added to a group SHIFTS every ordinal after it.
 *  Source: dex/evm/src/interfaces/IPool.sol */
export const OpType = {
  NONE: 0,
  MIGRATE_BASE_TOKEN: 1,
  UPDATE_ANCHOR: 2,
  UPDATE_TREASURY: 3,
  UPDATE_HOOK: 4,
  UPDATE_ORACLE: 5,
  ADD_ASSET: 6,
  UPDATE_RISK: 7,
  UPDATE_FEES: 8,
  UPDATE_PROFILE: 9,
  UPDATE_CURVE: 10,
  UPDATE_ASSET_PARAMS: 11,
} as const;
export type OpType = (typeof OpType)[keyof typeof OpType];

/** Risk-op selector for `Admin.batchRiskOp`.
 *  Source: dex/evm/src/interfaces/IAdmin.sol */
export const BatchOp = {
  HALT: 0,
  UNHALT: 1,
} as const;
export type BatchOp = (typeof BatchOp)[keyof typeof BatchOp];

/** Subsystem tag carried by `Err.NotFound` / `Err.FeatureDisabled` and friends. Ordered by MEANING, so ordinals move when a member joins its group.
 *  Source: shared/evm/src/Errors.sol */
export const Resource = {
  ASSET: 0,
  ORACLE: 1,
  FEED: 2,
  TREASURY: 3,
  GOVERNANCE: 4,
  SWAP: 5,
  LIABILITY_SWAP: 6,
  FLASH: 7,
  TRANSFER: 8,
} as const;
export type Resource = (typeof Resource)[keyof typeof Resource];

/** Index into the packed `AccessControl.GOV_DELAYS()` word (8 x uint32 seconds). See `govDelays` in src/governance.
 *  Source: shared/evm/src/Constants.sol */
export const Tier = {
  CRITICAL: 0,
  HIGH: 1,
  BASE: 2,
  LOW: 3,
  UPGRADE: 4,
  ROTATION: 5,
  FACTORY: 6,
} as const;
export type Tier = (typeof Tier)[keyof typeof Tier];

/** Key of `AccessControl.pendingRole` and of `queueRole`/`executeRole`/`cancelRole`.
 *  Source: shared/evm/src/access/AccessControl.sol */
export const Role = {
  NONE: 0,
  FACTORY: 1,
  TREASURY: 2,
  TREASURY_OWNER: 3,
} as const;
export type Role = (typeof Role)[keyof typeof Role];

// dex/evm/src/libraries/PoolConstantsLib.sol
export const HALT_RISK_BIT = 1;
export const HALT_GUARDIAN_BIT = 64;
export const HALT_MASK = 65;
export const SWAP_ENABLED_BIT = 2;
export const LIABILITY_SWAP_ENABLED_BIT = 4;
export const FLASH_ENABLED_BIT = 16;
export const FEED_HALT_BIT = 1;
export const MAX_CONFIDENCE_HALT_BPS = 1000;
export const MAX_DISPERSION_PBPS = 900000;
export const HOOK_PRE_OUTFLOW = 1;
export const HOOK_POST_INFLOW = 2;

// dex/evm/src/libraries/Pricing.sol
export const STALE_Z = 100;
export const STALE_GRACE_CAP_SECS = 30;

/**
 * Ops whose timelock key ignores `subject` (`Admin._keyOf` returns `_key(pool, opId)`). Every
 * other op keys on `(pool, opId, subject)`, so cancelling one with `subject = 0` computes a key
 * nothing was queued under and reverts `NoPending` instead of vetoing.
 */
export const POOL_SCOPED_OPS: readonly OpType[] = [
  OpType.MIGRATE_BASE_TOKEN,
  OpType.UPDATE_TREASURY,
  OpType.UPDATE_FEES,
];
