/** Regenerate `src/eth/rpcs.generated.ts` from the one RPC list, dex-evm `deployments/chains.json`
 *  `.rpc` (kept by `refresh-rpcs.ts`).
 *
 *   BTR_DEX_EVM=../dex-evm bun scripts/gen-rpcs.ts
 *
 * Only each chain's top rows land here: they go to the wallet's network prompt and to the browser's
 * residual reads, where a long list is a long list of third parties seeing a user's address. The
 * file's order is the back's (capacity), so the pick is NOT just the first two: not `paid`, and
 * ranked, among `browser` rows (any row when a chain has none), trusted host (see `lib/rpcUrl.ts`) with a real batch (`batch_max` >= 16, or unmeasured)
 * first, trusted next, wide-batch next, then the rest, ties in file order. The browser's multicall
 * coalescer sends wide batches, so `test/refresh-rpcs.test.ts` fails when a SERVED chain's picks
 * cannot take one. Every pick must pass `unusable`: a hand-edited key or http URL fails the run
 * rather than reaching a public file, a CSP header and a wallet prompt. The output is committed (a
 * Docker build has no sibling); `test/refresh-rpcs.test.ts` fails when it drifts. */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { $ } from 'bun';
import { norm, trusted, unusable } from './lib/rpcUrl';

/** RPCs handed to a wallet or read from a browser, per chain. */
export const TOP = 2;
const MIN_BATCH = 16;

type Row = string | { url: string; batch_max?: number; paid?: boolean; browser?: boolean };

export function rpcsFromChains(file: { rpc: Record<string, Row[]> }): Record<number, string[]> {
  const out: Record<number, string[]> = {};
  for (const [id, rows] of Object.entries(file.rpc).sort(([a], [b]) => Number(a) - Number(b))) {
    const rank = (r: Row) => {
      const url = norm(typeof r === 'string' ? r : r.url);
      const wide = typeof r === 'string' || !r.batch_max || r.batch_max >= MIN_BATCH;
      return (trusted(Number(id), url) ? 0 : 2) + (wide ? 0 : 1);
    };
    // Browser-callable rows only (`"browser": true`: a page on btr.markets passed CORS against
    // them). A chain with none falls back to any row: its list is a wallet prompt, and an
    // extension does not do CORS.
    const eligible = rows.filter((r) => typeof r === 'string' || !r.paid);
    const web = eligible.filter((r) => typeof r !== 'string' && r.browser);
    const picks = (web.length ? web : eligible)
      .map((r, i) => ({ r, i, k: rank(r) }))
      .sort((a, b) => a.k - b.k || a.i - b.i)
      .slice(0, TOP)
      .map(({ r }) => norm(typeof r === 'string' ? r : r.url));
    for (const u of picks) {
      const why = unusable(u, undefined);
      if (why) throw new Error(`gen-rpcs: chain ${id} ${u}: ${why}`);
    }
    if (picks.length) out[Number(id)] = picks;
  }
  return out;
}

export const render = (rpcs: Record<number, string[]>) =>
  `// GENERATED by scripts/gen-rpcs.ts from dex-evm deployments/chains.json \`.rpc\`: do not edit.
// Refresh the list with scripts/refresh-rpcs.ts, then regenerate.

export const CHAIN_RPCS: Readonly<Record<number, readonly string[]>> = {
${Object.entries(rpcs)
  .map(([id, urls]) => `  ${id}: [${urls.map((u) => JSON.stringify(u)).join(', ')}],`)
  .join('\n')}
};
`;

if (import.meta.main) {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const dexEvm = process.env.BTR_DEX_EVM ?? join(root, '..', 'dex-evm');
  const src = join(dexEvm, 'deployments', 'chains.json');
  if (!existsSync(src)) console.log(`gen-rpcs: ${src} absent: keeping the committed list`);
  else {
    const out = join(root, 'src', 'eth', 'rpcs.generated.ts');
    writeFileSync(out, render(rpcsFromChains(JSON.parse(readFileSync(src, 'utf8')))));
    try {
      await $`bunx biome format --write ${out}`.cwd(root).quiet();
    } catch {
      // formatting is cosmetic: a checkout without biome still gets the list
    }
    console.log(`gen-rpcs: wrote ${out}`);
  }
}
