// SPDX-License-Identifier: MIT
pragma solidity =0.8.35;

import {Test} from "forge-std/Test.sol";
import {NUQuartic as NUQ} from "../../src/libraries/NUQuartic.sol";

/// @title CurveStorageDump — generator for `sdk/test/fixtures/curve-storage.json`.
/// @notice NOT part of the dex suite. `gen-curve-storage.sh` copies this file into a pristine
///         snapshot of the dex repo at HEAD, runs it, and copies the JSON back. See that script for
///         the reproduction steps; nothing here is ever written into the dex repo.
/// @dev What the fixture certifies: `sdk/src/pool/storage.ts` `readCurve` hand-decodes the packed
///      `NUQuartic.Curve` header (m | 14×uint16 boundaries | dispRef at bit 232, flags at bit 248) and the two
///      words per segment (4×int64 | int64+int128). solc reports that struct as
///      `header:uint256 + segs:uint256[28]`, so NONE of that packing appears in `storageLayout` and
///      `test/storage-layout.test.ts` cannot see it. This dumps the RAW STORAGE WORDS `NUQuartic.set`
///      actually wrote, plus the library's OWN `rangeQ`/`evalQ`/`areaQ` readings of them, so the SDK
///      decoder is checked against Solidity rather than against a second copy of the same guess.
contract CurveStorageDumpTest is Test {
  using NUQ for NUQ.Curve;

  NUQ.Curve internal c;

  /// @dev Deliberately adversarial to the decoder: 4 NON-UNIFORM interior knots (so the 16-bit
  ///      boundary directory carries five distinct values, not a uniform ramp a wrong stride would
  ///      still reproduce), a NON-ANTISYMMETRIC monotone polygon (so `_centre` shifts and the stored
  ///      coefficients are not the caller's), coefficients that go negative (sign extension on both
  ///      the int64 lanes and the int128 prefix integral), and dispRef/flags both non-zero and
  ///      distinct (a swapped 232/248 read is otherwise invisible).
  uint16 internal constant DISP_REF = 1237;
  uint8 internal constant FLAGS = 1; // FLAG_REQUIRES_WALL

  function _input() internal pure returns (uint256[] memory interior, int256[] memory wQ) {
    interior = new uint256[](4);
    interior[0] = 1500;
    interior[1] = 3000;
    interior[2] = 6500;
    interior[3] = 9000;
    wQ = new int256[](9);
    wQ[0] = -37_000_000_001;
    wQ[1] = -36_000_000_000;
    wQ[2] = -21_500_000_000;
    wQ[3] = -3_000_000_000;
    wQ[4] = 4_250_000_000;
    wQ[5] = 19_750_000_000;
    wQ[6] = 33_000_000_000;
    wQ[7] = 40_000_000_000;
    wQ[8] = 41_500_000_000;
  }

  function test_dump_curve_storage() public {
    (uint256[] memory interior, int256[] memory wQ) = _input();
    c.set(interior, wQ, DISP_REF, FLAGS);

    // Raw storage, read back through `vm.load` — the bytes an eth_getStorageAt would return.
    // The base slot comes from the compiler (`c.slot`), not from a guess: forge-std's `Test` has
    // state of its own, so `c` is not at slot 0.
    uint256 base;
    assembly {
      base := c.slot
    }
    string memory words = "[";
    for (uint256 i = 0; i < 29; ++i) {
      words = string.concat(
        words,
        i == 0 ? "" : ",",
        "\"",
        vm.toString(vm.load(address(this), bytes32(base + i))),
        "\""
      );
    }
    words = string.concat(words, "]");

    uint256 header = c.header;
    (int256 y0, int256 span) = c.rangeQ(header);

    // The library's own readings of those same words — the differential the SDK must reproduce.
    string memory evals = "[";
    for (uint256 x = 0; x <= 10_000; x += 137) {
      evals = string.concat(
        evals, x == 0 ? "" : ",", "[", vm.toString(x), ",", vm.toString(c.evalQ(header, x)), "]"
      );
    }
    evals = string.concat(
      evals, ",[10000,", vm.toString(c.evalQ(header, 10_000)), "]]"
    );

    uint256[10] memory a1 = [uint256(0), 0, 1499, 1500, 1501, 3000, 4200, 6500, 8999, 9000];
    uint256[10] memory a2 =
      [uint256(10_000), 1500, 3001, 6500, 9000, 9000, 4201, 10_000, 9001, 10_000];
    string memory areas = "[";
    for (uint256 i = 0; i < a1.length; ++i) {
      areas = string.concat(
        areas,
        i == 0 ? "" : ",",
        "[",
        vm.toString(a1[i]),
        ",",
        vm.toString(a2[i]),
        ",",
        vm.toString(c.areaQ(header, a1[i], a2[i])),
        "]"
      );
    }
    areas = string.concat(areas, "]");

    string memory json = string.concat(
      "{\n  \"_note\": \"GENERATED by sdk/test/fixtures/gen-curve-storage.sh from dex@",
      vm.envOr("DEX_REV", string("unknown")),
      ". Do not hand-edit.\",\n  \"dispRef\": ",
      vm.toString(uint256(DISP_REF)),
      ",\n  \"flags\": ",
      vm.toString(uint256(FLAGS)),
      ",\n  \"interior\": [1500,3000,6500,9000],\n  \"wQ\": ["
    );
    for (uint256 i = 0; i < wQ.length; ++i) {
      json = string.concat(json, i == 0 ? "" : ",", "\"", vm.toString(wQ[i]), "\"");
    }
    json = string.concat(
      json,
      "],\n  \"y0\": \"",
      vm.toString(y0),
      "\",\n  \"span\": \"",
      vm.toString(span),
      "\",\n  \"words\": ",
      words,
      ",\n  \"evalQ\": ",
      evals,
      ",\n  \"areaQ\": ",
      areas,
      "\n}\n"
    );
    vm.writeFile("curve-storage.json", json);
  }
}
