// Generated by `bun scripts/gen.ts` from the sibling dex/shared checkouts. Do not edit by hand —
// `bun run gen:check` fails the build when this file and the contracts disagree.

/**
 * Deployed BTR venues, keyed by chain id
 * @module @btr-protocol/sdk/venues
 *
 * Source: `dex/evm/deployments/<chainId>.{deploy,pools}.json` — the broadcast record — plus the
 * pool rosters in `<chain>-risk-params.json`. A chain with no broadcast record is ABSENT, and
 * `registry.ts` throws on an absent chain rather than falling back, so a bot pointed at a chain
 * BTR is not deployed on cannot silently quote another chain's addresses.
 *
 * Feed NAMES are keys here; the on-chain `feedIds[]` ORDINAL is deliberately not, because the
 * deployment record does not carry it (forge sorts the keys it serialises, and the ordering is
 * split across two scripts). The only authority on an ordinal is the chain itself — see
 * `keepers/src/oracle/startup.rs`, which reads `feedIds(idx)` and refuses to start on a mismatch.
 */

import type { Address, Hex } from '../eth/types.js';

export interface ChainVenue {
  chainId: number;
  /** Singletons by name — `oracle`, `refOracle`, `poolFactory`, `faucet`, … */
  contracts: Record<string, Address>;
  /** Pool asset ERC20s by canonical symbol. First symbol of each roster is the USDC base. */
  tokens: Record<string, Address>;
  /** On-chain feed name (`USDT-USDC`, `USDC-USD`) ⇒ its `feedId`. */
  feedIds: Record<string, Hex>;
  /** Deployed cores with the symbols each one lists. */
  pools: Array<{ tag: string; address: Address; symbols: string[] }>;
  /** Feed names mirrored onto the reference oracle. */
  refFeeds: string[];
}

export const DEPLOYED_VENUES: Record<number, ChainVenue> = {
  11155111: {
    chainId: 11155111,
    contracts: {
      ac: '0xE2Eeb05eea5DfD87C3025e4fBe389D323Bd611AE',
      admin: '0x7708BF39Ca7cA42eE6d98b47E6ef809a56501A2a',
      distributor: '0x5845F2252A79696D401216219C0990982FC08835',
      faucet: '0xd26B2DC9A962b6000B277D37bcf8A7FAE2BE198D',
      flash: '0x42E2CD71031f30C0cb4D16B9A9F3598d3e8a405b',
      govToken: '0xbA0810D8aC1Ced307935fC116D7FbB399D3F0e1b',
      opsTreasuryProxy: '0x7407ee3bd8195103091c33788FB040d2520e69D4',
      oracle: '0xd3FB5bfF347265Aa7744582360Aaf3Eb6fdcf0e4',
      poolFactory: '0x9257A8F30e31e5Dc5f88C6623BB761b29D57Fd80',
      poolImpl: '0x44339E6451fE7858b1375BcF66b4f180945F235B',
      refOracle: '0x260ee8798eFb960017e8a6fC52E5B10695507670',
      staking: '0x2A9FF6e54eb735b6408945876498a286ffaa90D7',
      treasuryProxy: '0xCcf51E56b58c0abcD494700aE94e4ade17B9BE66',
    },
    tokens: {
      USDC: '0x35d8b13b44adbf6bfa968d9a9b4c0f66ab703bc8',
      USDT: '0xaa289b01a203bf31c326ec9435b50506e865b649',
      USDE: '0x69b1e0c437eb900cdb93beb80b7003c0adf6ec94',
      USDS: '0x7fddd2cece1f5151e23ebed86acd43ce931e74b7',
      DAI: '0x90f1036f562cc850d4a370c2dd8fd94a233e5e8d',
      USD1: '0x66600e17e418b6649562a039d32d6fcf6232e601',
      USDG: '0xa31e906896839642df11eb82aea7c442643ff6e8',
      PYUSD: '0x79929eaf36eac0640109d01bcc1f02db9dd1845f',
      RLUSD: '0x40c7c913bd001e9d99c427d52c2e59c01026a2b8',
      USDF: '0x16d720170b12c2811cd13e9d380d98db6d51a4e9',
      U: '0x77a95ab69bb0075aeec49ce1ed87515b55cbfd2c',
      GHO: '0x8796c36f8ba4b4224142fbfef747efbfec8f2dda',
      TUSD: '0x1b86f690dc359d3fb294930c5bb982503720da7f',
      USDTB: '0x6b65e577f893bcb24978a5cb5acc113d0c5a2eca',
      FDUSD: '0xb10ae8d3a15eb8ab98437d8a7611cd5e1ef73ab1',
      AUSD: '0x3cdb1a74b2bc2eab39a1134feb724a110c69b302',
      WETH: '0xe82c2371d8fff51492d6c6caf6e251b4949338d6',
      WBTC: '0xd26d0eec4b031cadd188b3808bf10ce91d379abf',
      cbBTC: '0x8dedc96eb7c72412ec9d07553b11fa482e515f5b',
      BNB: '0x05c07adbc119a1805d0b63c5862dbf2fbba56561',
      XAUT: '0x9b8d79878db7ee50fb9ef85d290e4cbdf26bee05',
      PAXG: '0x4b8bc47747d51890bac377546aee12502a56dd0e',
      EURC: '0xc6e514f3ab77d30778c3ad9a012075bedfc4c092',
      QCAD: '0x82131457FAa3218806d94056E316F00E0B2aA937',
      AUDF: '0x29D8E72D5eB0445dc36145044f5e489723d20E8a',
      BRLA: '0xa8357a783479bD13d254Fd2715987ab0a9CbDd69',
      JPYC: '0x904308A64E5c7aCfc23381D29C457AA7f4176f4f',
      KRW1: '0xA21c7E8328EaA898a39946FeCA981C0143366cC6',
    },
    feedIds: {
      'USDC-USD': '0xf097408cec312d10691ef8ff946389a6eab389bed1a574aa68222fdf45f1f1f2',
      'USDT-USDC': '0xe2ca0626104d5e537a71218cb1524d5f02623014f122c80e479cfb2698aaaef9',
      'USDE-USDC': '0xb235eefe16249c453be2a3d8b17d2648b3800ded997b2462fa2c05a92bfab2b8',
      'USDS-USDC': '0xb6361eb741b2e26a6713df09d0733cb0496e036a722cc80ba3aec2428feaf2de',
      'DAI-USDC': '0xa79f461569297cdfa4922e086316c5a076eb17e29ccb84da318cda002fb100c2',
      'USD1-USDC': '0x1e0351447b4c27b8c6a91336d78b45d771356fa89710de4241adb5ec7bc8adbc',
      'USDG-USDC': '0x2d57e58d54c6ad8940c0d313d8efad7f437c6478d7e0e61962515d868210e470',
      'PYUSD-USDC': '0x103d540aab5b8da5e55e3577b1fc1fb32834d83719b0ec3c1965da93ccee2338',
      'RLUSD-USDC': '0x62121c62a9bf512f7290db4c64ff874ed36801e2c587305622ab3c13eb463692',
      'USDF-USDC': '0x8eb03ba0c7206e7974e2b083ba20f042b0181512a2433d79699998a6e0dab5de',
      'U-USDC': '0xabf458a5978375d6037742d0aef47d257108d2caf9d332a0ed448f4c02475f13',
      'GHO-USDC': '0x740512af4d28192a5d2e01d2b38efd85733ff9539247ecebbbfde19760204f0a',
      'TUSD-USDC': '0x051334eafdb19cfe7d3181f79907b2f2e5fad69e3883eaeb29fbb9a37aa7aac7',
      'USDTB-USDC': '0x8dde29522c36d87452f22d6a0394339461f214dd0f3333f9f9e835ee29fb6821',
      'FDUSD-USDC': '0xd1cbd73596408f78397e1a17b9fd8248eb622a19186d159d18276505428e9b35',
      'AUSD-USDC': '0x6c5d7f72c1e08393b2835fe662ab0508645c3681f4bd4b15725a65185707be83',
      'WETH-USDC': '0x9f932869c5a713fda95a98fbf00efd7040421675d3d75148fee2c1a2cdb088be',
      'WBTC-USDC': '0x9a248df235b673abba59685693dc843b468f4edc17146c62dabd882fe69bdb03',
      'cbBTC-USDC': '0x0770b2902434aac390c910c38979d2bfbb2f5e2f43ab03c961af23172fcd4afa',
      'BNB-USDC': '0xa9ac83978b1f6fc516cd0c591e5656859849a28c1bdd4f6d9824ba0560cbb215',
      'XAUT-USDC': '0xfbd75bd57a7cda2e9e3b8409a6269cbf8fe7bf74d62f23822247ace2dafbe684',
      'PAXG-USDC': '0xb6e3605879a0b64f7984843b5fc9e3d5aafcbdf1874c08030d85e5e0d05dc5bb',
      'EURC-USDC': '0xc935b02202e468a1381f834951a37392b7c2b4ad80c8efe764f7ec9d5aca7504',
      'QCAD-USDC': '0xfdcbda586491de458657b1ec84cf53b85add9adf3f7ff929ee6f811d1447b8ab',
      'AUDF-USDC': '0xdc34b9876032749a1047d2af4ac6c8dd93a65093a17be701fbeae07f558cd8b7',
      'BRLA-USDC': '0x18085d4edb9a77884122a7d83e60bf0ff1fc64a631020887eae17791ab4c94ba',
      'JPYC-USDC': '0xcc35076388f2fb7e3a00d8e8d0530753b80853e7333aa2a11ff7ca090d217515',
      'KRW1-USDC': '0xc6cba05bf7e0af179298ee4318bd6ae95c30b337542881623d60eb6a1ff25967',
    },
    pools: [
      {
        tag: 'btr-stable',
        address: '0xfF6bf617cf2D3aB1608d6732cb5Efd8D184aDA8c',
        symbols: [
          'USDC',
          'USDT',
          'USDE',
          'USDS',
          'DAI',
          'USD1',
          'USDG',
          'PYUSD',
          'RLUSD',
          'USDF',
          'U',
          'GHO',
          'TUSD',
          'USDTB',
          'FDUSD',
          'AUSD',
        ],
      },
      {
        tag: 'btr-volatile',
        address: '0xFfa427bc61315c3Fd5C32157675b31135f910cAc',
        symbols: ['USDC', 'USDT', 'WETH', 'WBTC', 'cbBTC', 'BNB', 'XAUT', 'PAXG', 'EURC'],
      },
    ],
    refFeeds: [
      'WETH-USDC',
      'WBTC-USDC',
      'cbBTC-USDC',
      'BNB-USDC',
      'XAUT-USDC',
      'PAXG-USDC',
      'EURC-USDC',
      'USDC-USD',
    ],
  },
};
