// Generated by `bun scripts/gen.ts` from the sibling dex/shared checkouts. Do not edit by hand —
// `bun run gen:check` fails the build when this file and the contracts disagree.

/**
 * Deployed BTR venues, keyed by chain id
 * @module @btr-protocol/sdk/venues
 *
 * Source: `dex/evm/deployments/<chainId>.{deploy,pools}.json` — the broadcast record — plus the
 * pool rosters in `<chain>-risk-params.json`. A chain with no broadcast record is ABSENT, and
 * `registry.ts` throws on an absent chain rather than falling back, so a bot pointed at a chain
 * BTR is not deployed on cannot silently quote another chain's addresses.
 *
 * `feedIds` is keyed by feed NAME and ORDERED by on-chain ordinal: entry `n` is `feedIds[n]`, the
 * index every NXR-signed record carries. Arc's record states that order (`.feedOrder`); Sepolia's
 * predates it, so `scripts/gen.ts` replays the deploy scripts against the same risk-params they
 * consume and refuses any replay that does not reproduce the recorded feed set. The chain remains
 * the authority — `keepers/src/oracle/startup.rs` reads `feedIds(idx)` and refuses to start on a
 * mismatch — but nothing downstream hand-lists an ordinal any more.
 */

import type { Address, Hex } from '../eth/types.js';

export interface ChainVenue {
  chainId: number;
  /** Singletons by name — `oracle`, `refOracle`, `poolFactory`, `faucet`, … */
  contracts: Record<string, Address>;
  /** Pool asset ERC20s by canonical symbol. First symbol of each roster is the USDC base. */
  tokens: Record<string, Address>;
  /**
   * On-chain feed name (`USDT-USDC`, `USDC-USD`) ⇒ its `feedId`, in `feedIds[]` ordinal order.
   *
   * Faucet-twin aliases (`.feedTwins`) are APPENDED after the ordinal-carrying entries and share
   * a borrowed id, so entry `n` still names ordinal `n` but the tail is not an ordinal at all.
   * Read this by NAME. Anything that needs the order must stop at the recorded feed count.
   */
  feedIds: Record<string, Hex>;
  /**
   * On-chain feed name ⇒ its MITCH `tickerId` (decimal string), the key every signed record
   * carries. Content-derived, so it is the same on every chain — join a decoded record to a feed
   * through this, never through an array position. Absent for a pre-migration deployment record.
   */
  tickerIds: Record<string, string>;
  /** Router tag ⇒ the symbols that core is SCRIPTED to list, deployed or not. Twins are absent. */
  rosters: Record<string, string[]>;
  /**
   * Deployed cores with the symbols each one lists. A scripted-but-unbroadcast core is absent.
   * This is the ROUTABLE set and it is a superset of `rosters[tag]`: feedless faucet twins are
   * listed legs and quote, so they belong here and nowhere else.
   */
  pools: Array<{ tag: string; address: Address; symbols: string[] }>;
  /** Feed names mirrored onto the reference oracle. */
  refFeeds: string[];
}

export const DEPLOYED_VENUES: Record<number, ChainVenue> = {
  5042002: {
    chainId: 5042002,
    contracts: {
      ac: '0xa7Dc0A8815acCbDfc22619b6F65b2dE710Eb2A7B',
      admin: '0x35BB3BBeB86c7caee532083DAC639400912C8f00',
      faucet: '0x97BE19E537B9064f5c4984dD1e83Ad8b6aBe0cC3',
      flash: '0x544128B1F23D959F1B2660b1e392cb9D5e24d81f',
      oracle: '0xfe1Dc89FfE61CcDe653Fc05Bc5D6108417E5AF8e',
      poolFactory: '0xaF5Dfa6F3f549bAb1598Ff24d15c0cF9aCaA6Df7',
      poolImpl: '0xe3438c3BcD6921331D93950966c303453a607f51',
      refOracle: '0x317AE92F92bDDac76DA52D5D19832f3758FE3bbf',
    },
    tokens: {
      USDC: '0x3600000000000000000000000000000000000000',
      USDT: '0x878e27566Ab9E32534e306C26388dFcE82D0AB46',
      USDS: '0x66dbe40c8dc03f2C9e7A187F253e8889A03640c8',
      USD1: '0x0326748d09eD77D8C15fbf04d6277aE4CAF033f3',
      PYUSD: '0xeE12a7072779a4ab85f2DD2a1E163DbF164291f9',
      EURC: '0x89B50855Aa3bE2F677cD6303Cec089B5F319D72a',
      QCAD: '0x626eb915d4a4136F7c00352A54378d3A322488da',
      AUDF: '0x35c625c07ed4a9123ab863f6e8722c9210c808A3',
      JPYC: '0xA1fe5aDcB5f5DD1c21d372D18E7dF7fa5bfbc09e',
      KRW1: '0xee7D69C52c2F183A0389374E82ca841c5a463573',
      WETH: '0x89A9cD1dd6DE3ab7152EF9c7C5496c2946334D0D',
      WBTC: '0xF36eEe851bf3e76E464609a717bAE4a239A8cC7b',
      CBBTC: '0xbAA18E707E7b7fE9d1c0e4CeA61603035cb30C55',
      BNB: '0x49C710167A4b486F20f9437485D865D653806310',
      XAUT: '0x432A3248e91d8B6fd41A487dE8886E0B44Fb7a6D',
      PAXG: '0x96f953bAC2FF3829B4a526cacd858A5a22327E03',
      INTC: '0xd7A6216738Eba05C0ee47ff478e307bE5A94Dc95',
      AMD: '0x3e04aa20170944d29681a475Bb3dd0a1Bb421cCb',
      NVDA: '0xA4816856b8144ad1bb5a555A9Afa8B0f4B9FC8D0',
      ASML: '0x56520a1D0F047e748AA042975D95B6B3CD203a4d',
      SPCX: '0xf782226BB4B4C6F57F24D17a34c5C041482b4bE2',
      AVGO: '0x0458D9Fc5bd31b5Af3018Be9CfE91ecF4ABf9a7e',
      TSLA: '0xBA76ce34AC2c65813ee2c11F34Ad1523fE43CBac',
      MSFT: '0x83E43A65ce9E5aE1872a2363eD74D67C5A30fdb5',
      ORCL: '0x56F81D0831b9352e023266b72F38b4657baA32E8',
      META: '0x2767f2e94a7cF7935d59DdD7A5A30138369846e2',
      USDCB: '0x9A8Ea4AB461d0Db943ecB1B1e4CE0B68df9061CC',
      EURCB: '0xd9016a91387db71fbD07Cde32E900E17061dE5A1',
    },
    feedIds: {
      'USDT-USDC': '0xfa722ae80d6181ca931f45c80582c173b9c19cd30c1632e864e8f48ea62a6548',
      'USDS-USDC': '0x4d9df04bbf62ab0e8418c56a2fea063a7956bc08674600862a95970c583f3be5',
      'USD1-USDC': '0x4c7fec22c40835f297ef183fc68a20f5a965997cddedf9fcf5bd18b3d0898d85',
      'PYUSD-USDC': '0xd4ebce1baf00f6124f7a0bd347ef8170aaa7ce6e5dcf595879e3c61676921e99',
      'EURC-USDC': '0x9af29d8ae5269a47d972f6e5a188878d8e45cb2c7f7ce637492bdaef05a980be',
      'QCAD-USDC': '0x1c9b7f4cc3a7295cb420362f039e13565a7f80f9d0b7023405023d1db74735ea',
      'AUDF-USDC': '0x20dc0d8625fb1ae982d08763105cdce98e9a95ca59c4903190119c9fe88a47cd',
      'JPYC-USDC': '0xf3570f02e056765d6c42a5b3624067f3b80c80b9d22355c71b534c24eb8ae1e9',
      'KRW1-USDC': '0x2642c5e9691dbb5c5674a2a24ebb68e4df723f0656e3d4e2e45fa028c6caf650',
      'WETH-USDC': '0xacb54d59d0c847602722bfdec8aaaf92ead1385b3402cad482b3c6484a6efc1c',
      'WBTC-USDC': '0x63b49bbd6b259a4c3500020453ad775a8df2ff9e423fe5228644f18f495262bf',
      'CBBTC-USDC': '0x27f98ddc32af5a6272f676d428fd004af1718c18541118dc044c0ac3a2b612fd',
      'BNB-USDC': '0x5398b2b4caab86e6c562e30f6ecb15c4b87c20ed7595ad48b4048b62005b9888',
      'XAUT-USDC': '0xaf63e9c459822846879d75246ea10ee933d53a8f206c51c5150270aadd42625f',
      'PAXG-USDC': '0xb8b495d5826591b537a47841255ffbca7f1f0f56afff8f5e7bc565f1e20b338c',
      'USDC-USD': '0x0189091eac3c33dc88b48c58f75a1d978253e7fb2d4a1711b5701172b083c487',
      'INTC-USDC': '0x058dc9a04c0ebce2bb560948628013d466bdc2bfb8042e33d4a7a0dde2045fba',
      'AMD-USDC': '0xa6c9396c58cb1c50e6f2a6139404b148ecc7f86489d9d4faa01e3eb5228fc652',
      'NVDA-USDC': '0x9a0882814ace331414f8c2c7cb34e815e4c7092f8de7df39bba1fc92968deb69',
      'ASML-USDC': '0x6b434d49a41b22478b4b1d3fca59c90e5dbfc185cc1b5e2a9a3efd2f901e0c23',
      'SPCX-USDC': '0x1729d32f332780e7a939b7ca2a73ceb60cf507d64ed28e15023dad847f50fe47',
      'AVGO-USDC': '0x7d9c97fe812e6df01e2604baeade55e60503c8d793300e69d6da8efa52618b54',
      'TSLA-USDC': '0x91a8aa38cb67e3a567c5b58b125e69e218c5a97677de4b4ce327a1bd281e0952',
      'MSFT-USDC': '0x778b165de0bfe24e8806a0334dabd237c8f5844fb3d60a8d5b623d352120e784',
      'ORCL-USDC': '0x83c6210ed83e6bbd8db6d6dd43893d46cbc0a20efce89c30f6be2ce536ea74db',
      'META-USDC': '0x2d2201820627f4019b4ddd9d9742fc14a750d4df2f5413961e91c03e8af9581a',
      'USDCB-USDC': '0xfa722ae80d6181ca931f45c80582c173b9c19cd30c1632e864e8f48ea62a6548',
      'EURCB-USDC': '0x9af29d8ae5269a47d972f6e5a188878d8e45cb2c7f7ce637492bdaef05a980be',
    },
    tickerIds: {
      'USDT-USDC': '451698500104617984',
      'USDS-USDC': '448399965221289984',
      'USD1-USDC': '442022797780189184',
      'PYUSD-USDC': '445981039640182784',
      'EURC-USDC': '439219043129360384',
      'QCAD-USDC': '456096546615721984',
      'AUDF-USDC': '456206497778499584',
      'JPYC-USDC': '456426400104054784',
      'KRW1-USDC': '456536351266832384',
      'WETH-USDC': '438724262896861184',
      'WBTC-USDC': '453457718709059584',
      'CBBTC-USDC': '436635190804086784',
      'BNB-USDC': '434436167548534784',
      'XAUT-USDC': '454557230336835584',
      'PAXG-USDC': '454447279174057984',
      'USDC-USD': '452687840255410176',
      'INTC-USDC': '7687117506347008',
      'AMD-USDC': '166457972359168',
      'NVDA-USDC': '11205554715230208',
      'ASML-USDC': '1134028204802048',
      'SPCX-USDC': '14102767854419968',
      'AVGO-USDC': '1947666809356288',
      'TSLA-USDC': '15075835645001728',
      'MSFT-USDC': '10007087040954368',
      'ORCL-USDC': '11425457040785408',
      'META-USDC': '9930121227010048',
    },
    rosters: {
      'btr-stable': ['USDC', 'USDT', 'USDS', 'USD1', 'PYUSD'],
      'btr-fx': ['USDC', 'EURC', 'QCAD', 'AUDF', 'JPYC', 'KRW1'],
      'btr-crypto': ['USDC', 'USDT', 'WETH', 'WBTC', 'CBBTC', 'BNB', 'XAUT', 'PAXG', 'EURC'],
      'btr-stocks': [
        'USDC',
        'INTC',
        'AMD',
        'NVDA',
        'ASML',
        'SPCX',
        'AVGO',
        'TSLA',
        'MSFT',
        'ORCL',
        'META',
      ],
    },
    pools: [
      {
        tag: 'btr-stable',
        address: '0x8e33853c6c34F20c93385449afE9477029D45BFE',
        symbols: ['USDC', 'USDT', 'USDS', 'USD1', 'PYUSD', 'USDCB'],
      },
      {
        tag: 'btr-fx',
        address: '0xCbB809d5A5583301e7753D57D73A25C0d12EC232',
        symbols: ['USDC', 'EURC', 'QCAD', 'AUDF', 'JPYC', 'KRW1', 'USDCB', 'EURCB'],
      },
      {
        tag: 'btr-crypto',
        address: '0xACe9a150cdc3ab8AdBbc3e7CC5d5ce92485624F5',
        symbols: [
          'USDC',
          'USDT',
          'WETH',
          'WBTC',
          'CBBTC',
          'BNB',
          'XAUT',
          'PAXG',
          'EURC',
          'USDCB',
          'EURCB',
        ],
      },
      {
        tag: 'btr-stocks',
        address: '0xD98A734203A719d9CA26f562dc8bc9fcb55685e3',
        symbols: [
          'USDC',
          'INTC',
          'AMD',
          'NVDA',
          'ASML',
          'SPCX',
          'AVGO',
          'TSLA',
          'MSFT',
          'ORCL',
          'META',
          'USDCB',
        ],
      },
    ],
    refFeeds: [
      'USDT-USDC',
      'USDS-USDC',
      'USD1-USDC',
      'PYUSD-USDC',
      'EURC-USDC',
      'QCAD-USDC',
      'AUDF-USDC',
      'JPYC-USDC',
      'KRW1-USDC',
      'WETH-USDC',
      'WBTC-USDC',
      'CBBTC-USDC',
      'BNB-USDC',
      'XAUT-USDC',
      'PAXG-USDC',
      'INTC-USDC',
      'AMD-USDC',
      'NVDA-USDC',
      'ASML-USDC',
      'SPCX-USDC',
      'AVGO-USDC',
      'TSLA-USDC',
      'MSFT-USDC',
      'ORCL-USDC',
      'META-USDC',
    ],
  },
  11155111: {
    chainId: 11155111,
    contracts: {
      ac: '0xE2Eeb05eea5DfD87C3025e4fBe389D323Bd611AE',
      admin: '0x7708BF39Ca7cA42eE6d98b47E6ef809a56501A2a',
      distributor: '0x5845F2252A79696D401216219C0990982FC08835',
      faucet: '0xd26B2DC9A962b6000B277D37bcf8A7FAE2BE198D',
      flash: '0x42E2CD71031f30C0cb4D16B9A9F3598d3e8a405b',
      govToken: '0xbA0810D8aC1Ced307935fC116D7FbB399D3F0e1b',
      opsTreasuryProxy: '0x7407ee3bd8195103091c33788FB040d2520e69D4',
      oracle: '0xd3FB5bfF347265Aa7744582360Aaf3Eb6fdcf0e4',
      poolFactory: '0x9257A8F30e31e5Dc5f88C6623BB761b29D57Fd80',
      poolImpl: '0x44339E6451fE7858b1375BcF66b4f180945F235B',
      refOracle: '0x260ee8798eFb960017e8a6fC52E5B10695507670',
      staking: '0x2A9FF6e54eb735b6408945876498a286ffaa90D7',
      treasuryProxy: '0xCcf51E56b58c0abcD494700aE94e4ade17B9BE66',
    },
    tokens: {
      USDC: '0x35d8b13b44adbf6bfa968d9a9b4c0f66ab703bc8',
      USDT: '0xaa289b01a203bf31c326ec9435b50506e865b649',
      USDE: '0x69b1e0c437eb900cdb93beb80b7003c0adf6ec94',
      USDS: '0x7fddd2cece1f5151e23ebed86acd43ce931e74b7',
      DAI: '0x90f1036f562cc850d4a370c2dd8fd94a233e5e8d',
      USD1: '0x66600e17e418b6649562a039d32d6fcf6232e601',
      USDG: '0xa31e906896839642df11eb82aea7c442643ff6e8',
      PYUSD: '0x79929eaf36eac0640109d01bcc1f02db9dd1845f',
      RLUSD: '0x40c7c913bd001e9d99c427d52c2e59c01026a2b8',
      USDF: '0x16d720170b12c2811cd13e9d380d98db6d51a4e9',
      U: '0x77a95ab69bb0075aeec49ce1ed87515b55cbfd2c',
      GHO: '0x8796c36f8ba4b4224142fbfef747efbfec8f2dda',
      TUSD: '0x1b86f690dc359d3fb294930c5bb982503720da7f',
      USDTB: '0x6b65e577f893bcb24978a5cb5acc113d0c5a2eca',
      FDUSD: '0xb10ae8d3a15eb8ab98437d8a7611cd5e1ef73ab1',
      AUSD: '0x3cdb1a74b2bc2eab39a1134feb724a110c69b302',
      WETH: '0xe82c2371d8fff51492d6c6caf6e251b4949338d6',
      WBTC: '0xd26d0eec4b031cadd188b3808bf10ce91d379abf',
      cbBTC: '0x8dedc96eb7c72412ec9d07553b11fa482e515f5b',
      BNB: '0x05c07adbc119a1805d0b63c5862dbf2fbba56561',
      XAUT: '0x9b8d79878db7ee50fb9ef85d290e4cbdf26bee05',
      PAXG: '0x4b8bc47747d51890bac377546aee12502a56dd0e',
      EURC: '0xc6e514f3ab77d30778c3ad9a012075bedfc4c092',
      QCAD: '0x82131457FAa3218806d94056E316F00E0B2aA937',
      AUDF: '0x29D8E72D5eB0445dc36145044f5e489723d20E8a',
      BRLA: '0xa8357a783479bD13d254Fd2715987ab0a9CbDd69',
      JPYC: '0x904308A64E5c7aCfc23381D29C457AA7f4176f4f',
      KRW1: '0xA21c7E8328EaA898a39946FeCA981C0143366cC6',
    },
    feedIds: {
      'USDT-USDC': '0xe2ca0626104d5e537a71218cb1524d5f02623014f122c80e479cfb2698aaaef9',
      'USDE-USDC': '0xb235eefe16249c453be2a3d8b17d2648b3800ded997b2462fa2c05a92bfab2b8',
      'USDS-USDC': '0xb6361eb741b2e26a6713df09d0733cb0496e036a722cc80ba3aec2428feaf2de',
      'DAI-USDC': '0xa79f461569297cdfa4922e086316c5a076eb17e29ccb84da318cda002fb100c2',
      'USD1-USDC': '0x1e0351447b4c27b8c6a91336d78b45d771356fa89710de4241adb5ec7bc8adbc',
      'USDG-USDC': '0x2d57e58d54c6ad8940c0d313d8efad7f437c6478d7e0e61962515d868210e470',
      'PYUSD-USDC': '0x103d540aab5b8da5e55e3577b1fc1fb32834d83719b0ec3c1965da93ccee2338',
      'RLUSD-USDC': '0x62121c62a9bf512f7290db4c64ff874ed36801e2c587305622ab3c13eb463692',
      'USDF-USDC': '0x8eb03ba0c7206e7974e2b083ba20f042b0181512a2433d79699998a6e0dab5de',
      'U-USDC': '0xabf458a5978375d6037742d0aef47d257108d2caf9d332a0ed448f4c02475f13',
      'GHO-USDC': '0x740512af4d28192a5d2e01d2b38efd85733ff9539247ecebbbfde19760204f0a',
      'TUSD-USDC': '0x051334eafdb19cfe7d3181f79907b2f2e5fad69e3883eaeb29fbb9a37aa7aac7',
      'USDTB-USDC': '0x8dde29522c36d87452f22d6a0394339461f214dd0f3333f9f9e835ee29fb6821',
      'FDUSD-USDC': '0xd1cbd73596408f78397e1a17b9fd8248eb622a19186d159d18276505428e9b35',
      'AUSD-USDC': '0x6c5d7f72c1e08393b2835fe662ab0508645c3681f4bd4b15725a65185707be83',
      'WETH-USDC': '0x9f932869c5a713fda95a98fbf00efd7040421675d3d75148fee2c1a2cdb088be',
      'WBTC-USDC': '0x9a248df235b673abba59685693dc843b468f4edc17146c62dabd882fe69bdb03',
      'cbBTC-USDC': '0x0770b2902434aac390c910c38979d2bfbb2f5e2f43ab03c961af23172fcd4afa',
      'BNB-USDC': '0xa9ac83978b1f6fc516cd0c591e5656859849a28c1bdd4f6d9824ba0560cbb215',
      'XAUT-USDC': '0xfbd75bd57a7cda2e9e3b8409a6269cbf8fe7bf74d62f23822247ace2dafbe684',
      'PAXG-USDC': '0xb6e3605879a0b64f7984843b5fc9e3d5aafcbdf1874c08030d85e5e0d05dc5bb',
      'EURC-USDC': '0xc935b02202e468a1381f834951a37392b7c2b4ad80c8efe764f7ec9d5aca7504',
      'USDC-USD': '0xf097408cec312d10691ef8ff946389a6eab389bed1a574aa68222fdf45f1f1f2',
      'QCAD-USDC': '0xfdcbda586491de458657b1ec84cf53b85add9adf3f7ff929ee6f811d1447b8ab',
      'AUDF-USDC': '0xdc34b9876032749a1047d2af4ac6c8dd93a65093a17be701fbeae07f558cd8b7',
      'BRLA-USDC': '0x18085d4edb9a77884122a7d83e60bf0ff1fc64a631020887eae17791ab4c94ba',
      'JPYC-USDC': '0xcc35076388f2fb7e3a00d8e8d0530753b80853e7333aa2a11ff7ca090d217515',
      'KRW1-USDC': '0xc6cba05bf7e0af179298ee4318bd6ae95c30b337542881623d60eb6a1ff25967',
    },
    tickerIds: {
      'USDT-USDC': '451698500104617984',
      'USDE-USDC': '438284458245750784',
      'USDS-USDC': '448399965221289984',
      'DAI-USDC': '437624751269085184',
      'USD1-USDC': '442022797780189184',
      'USDG-USDC': '453897523360169984',
      'PYUSD-USDC': '445981039640182784',
      'RLUSD-USDC': '447520355919069184',
      'USDF-USDC': '439383969873526784',
      'U-USDC': '454887083825168384',
      'GHO-USDC': '432566997781315584',
      'TUSD-USDC': '452358207081283584',
      'USDTB-USDC': '438394409408528384',
      'FDUSD-USDC': '439603872199081984',
      'AUSD-USDC': '432896851269648384',
      'WETH-USDC': '438724262896861184',
      'WBTC-USDC': '453457718709059584',
      'cbBTC-USDC': '436635190804086784',
      'BNB-USDC': '434436167548534784',
      'XAUT-USDC': '454557230336835584',
      'PAXG-USDC': '454447279174057984',
      'EURC-USDC': '439219043129360384',
      'USDC-USD': '452687840255410176',
      'QCAD-USDC': '456096546615721984',
      'AUDF-USDC': '456206497778499584',
      'BRLA-USDC': '456316448941277184',
      'JPYC-USDC': '456426400104054784',
      'KRW1-USDC': '456536351266832384',
    },
    rosters: {
      'btr-stable': [
        'USDC',
        'USDT',
        'USDE',
        'USDS',
        'DAI',
        'USD1',
        'USDG',
        'PYUSD',
        'RLUSD',
        'USDF',
        'U',
        'GHO',
        'TUSD',
        'USDTB',
        'FDUSD',
        'AUSD',
      ],
      'btr-volatile': ['USDC', 'USDT', 'WETH', 'WBTC', 'cbBTC', 'BNB', 'XAUT', 'PAXG', 'EURC'],
      'btr-fx': ['USDC', 'EURC', 'QCAD', 'AUDF', 'BRLA', 'JPYC', 'KRW1'],
    },
    pools: [
      {
        tag: 'btr-stable',
        address: '0xfF6bf617cf2D3aB1608d6732cb5Efd8D184aDA8c',
        symbols: [
          'USDC',
          'USDT',
          'USDE',
          'USDS',
          'DAI',
          'USD1',
          'USDG',
          'PYUSD',
          'RLUSD',
          'USDF',
          'U',
          'GHO',
          'TUSD',
          'USDTB',
          'FDUSD',
          'AUSD',
        ],
      },
      {
        tag: 'btr-volatile',
        address: '0xFfa427bc61315c3Fd5C32157675b31135f910cAc',
        symbols: ['USDC', 'USDT', 'WETH', 'WBTC', 'cbBTC', 'BNB', 'XAUT', 'PAXG', 'EURC'],
      },
    ],
    refFeeds: [
      'WETH-USDC',
      'WBTC-USDC',
      'cbBTC-USDC',
      'BNB-USDC',
      'XAUT-USDC',
      'PAXG-USDC',
      'EURC-USDC',
      'USDC-USD',
    ],
  },
};
