// GENERATED by `bun scripts/gen-venues.ts` from dex-evm/deployments/<chainId>.{deploy,pools}.json
// + <slug>.manifest.json. Do not edit: fix the record and regenerate.

/**
 * Deployed BTR venues, keyed by chain id
 * @module @btr-protocol/sdk/venues
 *
 * A chain with no broadcast core is ABSENT, and `registry.ts` throws on an absent chain rather
 * than falling back, so a bot pointed at a chain BTR is not deployed on cannot silently quote
 * another chain's addresses.
 */

import type { Address, Hex } from '../eth/types.js';

export interface ChainVenue {
  chainId: number;
  /** Every top-level non-role, non-token, non-core address in the records, by record key
   *  (nested `libraries` and `<key>Receipts` are not venues). P8 aliases are the design: the
   *  factory is `oracle` = `poolFactory` = `verifierP` and serves both tiers (no `refOracle`),
   *  `store` = `poolImpl`. `verifierR` is the reference tier's derived EIP-712 verifyingContract
   *  (`MarkStoreBase.tierVerifier`): no code. */
  contracts: Record<string, Address>;
  /** Manifest tokens by symbol. The hub (roster index 0) is the base of every core. */
  tokens: Record<string, Address>;
  /** On-chain feed name (`USDT-USDC`, `USDC-USD`) ⇒ feedId, in globalIndex order. */
  feedIds: Record<string, Hex>;
  /** Same keys ⇒ MITCH tickerId (decimal string; feedId = bytes32(ticker)). */
  tickerIds: Record<string, string>;
  /** Pool tag ⇒ the symbols the manifest scripts for that core, broadcast or not. */
  rosters: Record<string, string[]>;
  /** Pool tag ⇒ manifest `pools.<key>.{code,name}`, input of `lpToken`. */
  lp: Record<string, { code: string; name: string }>;
  /** Broadcast cores only: the routable set. */
  pools: Array<{ tag: string; address: Address; symbols: string[] }>;
  /** Feed names read off the reference tier, union of every core's `<key>RefFeeds`. */
  refFeeds: string[];
}

export const DEPLOYED_VENUES: Record<number, ChainVenue> = {
  '143': {
    chainId: 143,
    contracts: {
      ac: '0xbbbBBB289736272E5fb64f284D176Ffb49d6C6cF',
      admin: '0xBbbBBb226988e555e7a175D8e07Eef61CDa84CD2',
      adminImpl: '0x504447524Cf3953E0894185C2f45145F64639A64',
      coopArb: '0xbbbbbbb1B6E6e1b035e0f9815c67E2968dF8e827',
      flash: '0xBBBBBBBb1bCF78304ECbe4c7fC7c21244Bb55D3a',
      flashImpl: '0x5E5eC44821302140d81F9ABC90492aBD195dC496',
      logic: '0xECB9d44832dFdED469D091627D1463Eb4A28a00E',
      markStoreLogic: '0xECB9d44832dFdED469D091627D1463Eb4A28a00E',
      oracle: '0xbBBbBBBb323D7f7E51976b8A8DF2Bb4B4608d9B3',
      poolFactory: '0xbBBbBBBb323D7f7E51976b8A8DF2Bb4B4608d9B3',
      poolImpl: '0xF69c573ED360805308821198a1E24c1A39Cd0D4F',
      router: '0xBBBbbbbBB698143c38935b29b65B72eBe18C393c',
      store: '0xF69c573ED360805308821198a1E24c1A39Cd0D4F',
      verifierP: '0xbBBbBBBb323D7f7E51976b8A8DF2Bb4B4608d9B3',
      verifierR: '0x27cf4711937B0154ba70D020eD238D941b586966',
    },
    tokens: {
      USDC: '0x754704Bc059F8C67012fEd69BC8A327a5aafb603',
      WMON: '0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A',
      CBBTC: '0xd18B7EC58Cdf4876f6AFebd3Ed1730e4Ce10414b',
      WBTC: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
      WETH: '0xEE8c0E9f1BFFb4Eb878d8f15f368A02a35481242',
      XAUT0: '0x01bFF41798a0BcF287b996046Ca68b395DbC1071',
    },
    feedIds: {
      'USDC-USD': '0x0000000000000000000000000000000000000000000000000648453138900000',
      'WMON-USDC': '0x000000000000000000000000000000000000000000000000065b056484500000',
      'CBBTC-USDC': '0x000000000000000000000000000000000000000000000000060a8d6484500000',
      'WBTC-USDC': '0x000000000000000000000000000000000000000000000000064b016484500000',
      'WETH-USDC': '0x0000000000000000000000000000000000000000000000000616a96484500000',
      'XAUT0-USDC': '0x000000000000000000000000000000000000000000000000064ee96484500000',
    },
    tickerIds: {
      'USDC-USD': '452687840255410176',
      'WMON-USDC': '457965716382941184',
      'CBBTC-USDC': '435315776850755584',
      'WBTC-USDC': '453457718709059584',
      'WETH-USDC': '438724262896861184',
      'XAUT0-USDC': '454557230336835584',
    },
    rosters: {
      'btr-core': ['USDC', 'WMON', 'CBBTC', 'WBTC', 'WETH', 'XAUT0'],
    },
    lp: {
      'btr-core': {
        code: 'C',
        name: 'Core',
      },
    },
    pools: [
      {
        tag: 'btr-core',
        address: '0xbBbbBBBB7a74F5D3C81bd2beF3026F1Aa6539b5C',
        symbols: ['USDC', 'WMON', 'CBBTC', 'WBTC', 'WETH', 'XAUT0'],
      },
    ],
    refFeeds: ['WMON-USDC', 'CBBTC-USDC', 'WBTC-USDC', 'WETH-USDC', 'XAUT0-USDC'],
  },
  '5042002': {
    chainId: 5042002,
    contracts: {
      ac: '0xbbbBBB289736272E5fb64f284D176Ffb49d6C6cF',
      admin: '0xBbbBBb226988e555e7a175D8e07Eef61CDa84CD2',
      adminImpl: '0xa5859ABBeC3a44AD33D84C8baDaf0de5472339f2',
      faucet: '0x482178f9d6A5cf33E044e4B00076E4799a7080c8',
      flash: '0xBBBBBBBb1bCF78304ECbe4c7fC7c21244Bb55D3a',
      flashImpl: '0x504447524Cf3953E0894185C2f45145F64639A64',
      logic: '0x138F360aCAc96727ACc1a38E4EF6d1704ee5edc1',
      markStoreLogic: '0x138F360aCAc96727ACc1a38E4EF6d1704ee5edc1',
      oracle: '0xbBBbBBBb323D7f7E51976b8A8DF2Bb4B4608d9B3',
      poolFactory: '0xbBBbBBBb323D7f7E51976b8A8DF2Bb4B4608d9B3',
      poolImpl: '0xECB9d44832dFdED469D091627D1463Eb4A28a00E',
      router: '0xBBBbbbbBB698143c38935b29b65B72eBe18C393c',
      store: '0xECB9d44832dFdED469D091627D1463Eb4A28a00E',
      verifierP: '0xbBBbBBBb323D7f7E51976b8A8DF2Bb4B4608d9B3',
      verifierR: '0x27cf4711937B0154ba70D020eD238D941b586966',
    },
    tokens: {
      USDCB: '0x9A8Ea4AB461d0Db943ecB1B1e4CE0B68df9061CC',
      EURC: '0x89B50855Aa3bE2F677cD6303Cec089B5F319D72a',
      USDT: '0x878e27566Ab9E32534e306C26388dFcE82D0AB46',
      USDS: '0x66dbe40c8dc03f2C9e7A187F253e8889A03640c8',
      USD1: '0x0326748d09eD77D8C15fbf04d6277aE4CAF033f3',
      PYUSD: '0xeE12a7072779a4ab85f2DD2a1E163DbF164291f9',
      QCAD: '0x626eb915d4a4136F7c00352A54378d3A322488da',
      AUDF: '0x35c625c07ed4a9123ab863f6e8722c9210c808A3',
      JPYC: '0xA1fe5aDcB5f5DD1c21d372D18E7dF7fa5bfbc09e',
      KRW1: '0xee7D69C52c2F183A0389374E82ca841c5a463573',
      WETH: '0x89A9cD1dd6DE3ab7152EF9c7C5496c2946334D0D',
      WBTC: '0xF36eEe851bf3e76E464609a717bAE4a239A8cC7b',
      CBBTC: '0xbAA18E707E7b7fE9d1c0e4CeA61603035cb30C55',
      BNB: '0x49C710167A4b486F20f9437485D865D653806310',
      XAUT: '0x432A3248e91d8B6fd41A487dE8886E0B44Fb7a6D',
      PAXG: '0x96f953bAC2FF3829B4a526cacd858A5a22327E03',
      INTC: '0xd7A6216738Eba05C0ee47ff478e307bE5A94Dc95',
      AMD: '0x3e04aa20170944d29681a475Bb3dd0a1Bb421cCb',
      NVDA: '0xA4816856b8144ad1bb5a555A9Afa8B0f4B9FC8D0',
      ASML: '0x56520a1D0F047e748AA042975D95B6B3CD203a4d',
      SPCX: '0xf782226BB4B4C6F57F24D17a34c5C041482b4bE2',
      AVGO: '0x0458D9Fc5bd31b5Af3018Be9CfE91ecF4ABf9a7e',
      TSLA: '0xBA76ce34AC2c65813ee2c11F34Ad1523fE43CBac',
      MSFT: '0x83E43A65ce9E5aE1872a2363eD74D67C5A30fdb5',
      ORCL: '0x56F81D0831b9352e023266b72F38b4657baA32E8',
      META: '0x2767f2e94a7cF7935d59DdD7A5A30138369846e2',
    },
    feedIds: {
      'USDC-USD': '0x0000000000000000000000000000000000000000000000000648453138900000',
      'USDT-USDC': '0x0000000000000000000000000000000000000000000000000644c16484500000',
      'USDS-USDC': '0x0000000000000000000000000000000000000000000000000639096484500000',
      'USD1-USDC': '0x0000000000000000000000000000000000000000000000000622616484500000',
      'PYUSD-USDC': '0x0000000000000000000000000000000000000000000000000630716484500000',
      'EURC-USDC': '0x00000000000000000000000000000000000000000000000006186b6484500000',
      'QCAD-USDC': '0x0000000000000000000000000000000000000000000000000654616484500000',
      'AUDF-USDC': '0x0000000000000000000000000000000000000000000000000654c56484500000',
      'JPYC-USDC': '0x00000000000000000000000000000000000000000000000006558d6484500000',
      'KRW1-USDC': '0x0000000000000000000000000000000000000000000000000655f16484500000',
      'WETH-USDC': '0x0000000000000000000000000000000000000000000000000616a96484500000',
      'WBTC-USDC': '0x000000000000000000000000000000000000000000000000064b016484500000',
      'CBBTC-USDC': '0x000000000000000000000000000000000000000000000000060f3d6484500000',
      'BNB-USDC': '0x00000000000000000000000000000000000000000000000006076d6484500000',
      'XAUT-USDC': '0x000000000000000000000000000000000000000000000000064ee96484500000',
      'PAXG-USDC': '0x000000000000000000000000000000000000000000000000064e856484500000',
      'INTC-USDC': '0x000000000000000000000000000000000000000000000000001b4f6484500000',
      'AMD-USDC': '0x0000000000000000000000000000000000000000000000000000976484500000',
      'NVDA-USDC': '0x0000000000000000000000000000000000000000000000000027cf6484500000',
      'ASML-USDC': '0x0000000000000000000000000000000000000000000000000004076484500000',
      'SPCX-USDC': '0x00000000000000000000000000000000000000000000000000321a6484500000',
      'AVGO-USDC': '0x0000000000000000000000000000000000000000000000000006eb6484500000',
      'TSLA-USDC': '0x00000000000000000000000000000000000000000000000000358f6484500000',
      'MSFT-USDC': '0x00000000000000000000000000000000000000000000000000238d6484500000',
      'ORCL-USDC': '0x0000000000000000000000000000000000000000000000000028976484500000',
      'META-USDC': '0x0000000000000000000000000000000000000000000000000023476484500000',
    },
    tickerIds: {
      'USDC-USD': '452687840255410176',
      'USDT-USDC': '451698500104617984',
      'USDS-USDC': '448399965221289984',
      'USD1-USDC': '442022797780189184',
      'PYUSD-USDC': '445981039640182784',
      'EURC-USDC': '439219043129360384',
      'QCAD-USDC': '456096546615721984',
      'AUDF-USDC': '456206497778499584',
      'JPYC-USDC': '456426400104054784',
      'KRW1-USDC': '456536351266832384',
      'WETH-USDC': '438724262896861184',
      'WBTC-USDC': '453457718709059584',
      'CBBTC-USDC': '436635190804086784',
      'BNB-USDC': '434436167548534784',
      'XAUT-USDC': '454557230336835584',
      'PAXG-USDC': '454447279174057984',
      'INTC-USDC': '7687117506347008',
      'AMD-USDC': '166457972359168',
      'NVDA-USDC': '11205554715230208',
      'ASML-USDC': '1134028204802048',
      'SPCX-USDC': '14102767854419968',
      'AVGO-USDC': '1947666809356288',
      'TSLA-USDC': '15075835645001728',
      'MSFT-USDC': '10007087040954368',
      'ORCL-USDC': '11425457040785408',
      'META-USDC': '9930121227010048',
    },
    rosters: {
      'btr-stable-core': ['USDCB', 'USDT', 'USDS', 'USD1', 'PYUSD'],
      'btr-fx-core': ['USDCB', 'EURC', 'QCAD', 'AUDF', 'JPYC', 'KRW1'],
      'btr-crypto-core': ['USDCB', 'USDT', 'WETH', 'WBTC', 'CBBTC', 'BNB', 'XAUT', 'PAXG', 'EURC'],
      'btr-stocks-core': [
        'USDCB',
        'INTC',
        'AMD',
        'NVDA',
        'ASML',
        'SPCX',
        'AVGO',
        'TSLA',
        'MSFT',
        'ORCL',
        'META',
      ],
    },
    lp: {
      'btr-stable-core': {
        code: 'S',
        name: 'Stable',
      },
      'btr-fx-core': {
        code: 'F',
        name: 'Forex',
      },
      'btr-crypto-core': {
        code: 'X',
        name: 'Crypto',
      },
      'btr-stocks-core': {
        code: 'E',
        name: 'Equity',
      },
    },
    pools: [
      {
        tag: 'btr-stable-core',
        address: '0xbbbBbbB9B0335cc991924E1F5b59f0d4D88f1dE0',
        symbols: ['USDCB', 'USDT', 'USDS', 'USD1', 'PYUSD'],
      },
      {
        tag: 'btr-crypto-core',
        address: '0xbbBbBBbb09Fb9E10d8C178433368e32E89aBAd4b',
        symbols: ['USDCB', 'USDT', 'WETH', 'WBTC', 'CBBTC', 'BNB', 'XAUT', 'PAXG', 'EURC'],
      },
    ],
    refFeeds: [
      'USDT-USDC',
      'USDS-USDC',
      'USD1-USDC',
      'PYUSD-USDC',
      'WETH-USDC',
      'WBTC-USDC',
      'CBBTC-USDC',
      'BNB-USDC',
      'XAUT-USDC',
      'PAXG-USDC',
      'EURC-USDC',
    ],
  },
};
